version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: octonyah-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'

  redis:
    image: redis:7-alpine
    container_name: octonyah-redis
    restart: unless-stopped
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: octonyah-rabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:16
    container_name: octonyah-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: octonyah
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cms-service:
    build:
      context: .
      dockerfile: apps/cms-service/Dockerfile
    container_name: octonyah-cms
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbitmq
    environment:
      NODE_ENV: production
      CMS_PORT: 3000
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: octonyah
      RABBITMQ_URL: amqp://rabbitmq:5672
      RABBITMQ_QUEUE: program-events
      RABBITMQ_PREFETCH: 1
    ports:
      - '3000:3000'

  discovery-service:
    build:
      context: .
      dockerfile: apps/discovery-service/Dockerfile
    container_name: octonyah-discovery
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - elasticsearch
    environment:
      NODE_ENV: production
      DISCOVERY_PORT: 3001
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: octonyah
      RABBITMQ_URL: amqp://rabbitmq:5672
      RABBITMQ_QUEUE: program-events
      RABBITMQ_PREFETCH: 1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      REDIS_TTL_SECONDS: 300
      ELASTICSEARCH_NODE: http://elasticsearch:9200
      ELASTICSEARCH_INDEX: programs
    ports:
      - '3001:3001'

volumes:
  postgres_data:

